server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: camiones
          uri: http://localhost:8082
          predicates:
            - Path=/camiones/**
        - id: clientes-solicitudes
          uri: http://localhost:8081
          predicates:
            - Path=/solicitudes/**, /eventos-seguimiento/**
